// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Vectis.Web.Data;

#nullable disable

namespace Vectis.Web.Data.Migrations
{
    [DbContext(typeof(VectisDbContext))]
    [Migration("20260726010834_AddAutomaticNotificationSending")]
    partial class AddAutomaticNotificationSending
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Vectis.Web.Data.Entities.AuditEntryEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("EntityId")
                        .HasColumnType("uuid");

                    b.Property<string>("EntityName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NewValue")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("OldValue")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("audit_entries", (string)null);
                });

            modelBuilder.Entity("Vectis.Web.Data.Entities.BabyEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateOnly>("BirthDate")
                        .HasColumnType("date");

                    b.Property<decimal?>("CurrentWeightKg")
                        .HasColumnType("numeric");

                    b.Property<Guid>("FamilyId")
                        .HasColumnType("uuid");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("UsualBottleMl")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("FamilyId");

                    b.ToTable("babies", null, t =>
                        {
                            t.HasCheckConstraint("CK_babies_usual_bottle_positive", "\"UsualBottleMl\" > 0");
                        });
                });

            modelBuilder.Entity("Vectis.Web.Data.Entities.ConservationRuleEntity", b =>
                {
                    b.Property<string>("Location")
                        .HasColumnType("text");

                    b.Property<int>("DurationHours")
                        .HasColumnType("integer");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Location");

                    b.ToTable("conservation_rules", null, t =>
                        {
                            t.HasCheckConstraint("CK_conservation_rules_duration_positive", "\"DurationHours\" > 0");
                        });
                });

            modelBuilder.Entity("Vectis.Web.Data.Entities.FamilyEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CreatorUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CreatorUserId");

                    b.ToTable("families", (string)null);
                });

            modelBuilder.Entity("Vectis.Web.Data.Entities.FamilyInvitationEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("AcceptedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)");

                    b.Property<Guid>("FamilyId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("InvitedByUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("InvitedByUserId");

                    b.HasIndex("FamilyId", "Email", "Status");

                    b.ToTable("family_invitations", (string)null);
                });

            modelBuilder.Entity("Vectis.Web.Data.Entities.FamilyMemberEntity", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("FamilyId")
                        .HasColumnType("uuid");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("UserId", "FamilyId");

                    b.HasIndex("FamilyId");

                    b.ToTable("family_members", (string)null);
                });

            modelBuilder.Entity("Vectis.Web.Data.Entities.FeedingEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("BabyId")
                        .HasColumnType("uuid");

                    b.Property<int>("ConsumedQuantityMl")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("EndedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("FedByUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("LeftoverOutcome")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("LeftoverQuantityMl")
                        .HasColumnType("integer");

                    b.Property<string>("MilkType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("PreparedBottleId")
                        .HasColumnType("uuid");

                    b.Property<int>("PreparedQuantityMl")
                        .HasColumnType("integer");

                    b.Property<string>("Reaction")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("BabyId");

                    b.HasIndex("FedByUserId");

                    b.HasIndex("PreparedBottleId");

                    b.ToTable("feedings", null, t =>
                        {
                            t.HasCheckConstraint("CK_feedings_consumed_range", "\"ConsumedQuantityMl\" >= 0 AND \"ConsumedQuantityMl\" <= \"PreparedQuantityMl\"");

                            t.HasCheckConstraint("CK_feedings_leftover_non_negative", "\"LeftoverQuantityMl\" >= 0");

                            t.HasCheckConstraint("CK_feedings_prepared_positive", "\"PreparedQuantityMl\" > 0");
                        });
                });

            modelBuilder.Entity("Vectis.Web.Data.Entities.MilkContainerEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("BabyId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("EstimatedExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("InitialQuantityMl")
                        .HasColumnType("integer");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("PumpedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("PumpingSessionId")
                        .HasColumnType("uuid");

                    b.Property<int>("RemainingQuantityMl")
                        .HasColumnType("integer");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("PumpingSessionId");

                    b.HasIndex("BabyId", "EstimatedExpiresAt");

                    b.ToTable("milk_containers", null, t =>
                        {
                            t.HasCheckConstraint("CK_milk_containers_initial_positive", "\"InitialQuantityMl\" > 0");

                            t.HasCheckConstraint("CK_milk_containers_remaining_range", "\"RemainingQuantityMl\" >= 0 AND \"RemainingQuantityMl\" <= \"InitialQuantityMl\"");
                        });
                });

            modelBuilder.Entity("Vectis.Web.Data.Entities.NotificationDeliveryEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("FamilyId")
                        .HasColumnType("uuid");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RecipientEmail")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)");

                    b.Property<DateTimeOffset?>("SentAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("FamilyId", "Kind", "CreatedAt");

                    b.ToTable("notification_deliveries", (string)null);
                });

            modelBuilder.Entity("Vectis.Web.Data.Entities.NotificationPreferencesEntity", b =>
                {
                    b.Property<Guid>("FamilyId")
                        .HasColumnType("uuid");

                    b.Property<bool>("AutomaticEmailEnabled")
                        .HasColumnType("boolean");

                    b.Property<bool>("ExpiringSoonEnabled")
                        .HasColumnType("boolean");

                    b.Property<int>("ExpiringSoonHours")
                        .HasColumnType("integer");

                    b.Property<int>("PreparedBottleAgeMinutes")
                        .HasColumnType("integer");

                    b.Property<bool>("PreparedBottleAgingEnabled")
                        .HasColumnType("boolean");

                    b.Property<int>("StockLowBottleThreshold")
                        .HasColumnType("integer");

                    b.Property<bool>("StockLowEnabled")
                        .HasColumnType("boolean");

                    b.HasKey("FamilyId");

                    b.ToTable("notification_preferences", null, t =>
                        {
                            t.HasCheckConstraint("CK_notification_preferences_bottle_age_positive", "\"PreparedBottleAgeMinutes\" > 0");

                            t.HasCheckConstraint("CK_notification_preferences_expiring_hours_positive", "\"ExpiringSoonHours\" > 0");

                            t.HasCheckConstraint("CK_notification_preferences_stock_threshold_positive", "\"StockLowBottleThreshold\" >= 0");
                        });
                });

            modelBuilder.Entity("Vectis.Web.Data.Entities.PreparedBottleEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("BabyId")
                        .HasColumnType("uuid");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("PreparedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("PreparedByUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("TotalQuantityMl")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("BabyId");

                    b.HasIndex("PreparedByUserId");

                    b.ToTable("prepared_bottles", null, t =>
                        {
                            t.HasCheckConstraint("CK_prepared_bottles_total_positive", "\"TotalQuantityMl\" > 0");
                        });
                });

            modelBuilder.Entity("Vectis.Web.Data.Entities.PreparedBottleSourceEntity", b =>
                {
                    b.Property<Guid>("PreparedBottleId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ContainerId")
                        .HasColumnType("uuid");

                    b.Property<int>("QuantityMl")
                        .HasColumnType("integer");

                    b.HasKey("PreparedBottleId", "ContainerId");

                    b.HasIndex("ContainerId");

                    b.ToTable("prepared_bottle_sources", null, t =>
                        {
                            t.HasCheckConstraint("CK_prepared_bottle_sources_quantity_positive", "\"QuantityMl\" > 0");
                        });
                });

            modelBuilder.Entity("Vectis.Web.Data.Entities.PumpingSessionEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("BabyId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uuid");

                    b.Property<int?>("DurationMinutes")
                        .HasColumnType("integer");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("PumpedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Side")
                        .HasColumnType("text");

                    b.Property<int>("TotalQuantityMl")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("BabyId");

                    b.HasIndex("CreatedByUserId");

                    b.ToTable("pumping_sessions", null, t =>
                        {
                            t.HasCheckConstraint("CK_pumping_sessions_total_positive", "\"TotalQuantityMl\" > 0");
                        });
                });

            modelBuilder.Entity("Vectis.Web.Data.Entities.StockMovementEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Comment")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("ContainerId")
                        .HasColumnType("uuid");

                    b.Property<string>("NewLocation")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NewStatus")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PreviousLocation")
                        .HasColumnType("text");

                    b.Property<string>("PreviousStatus")
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ContainerId");

                    b.HasIndex("UserId");

                    b.ToTable("stock_movements", (string)null);
                });

            modelBuilder.Entity("Vectis.Web.Data.Entities.UserEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TimeZone")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("Vectis.Web.Data.Entities.AuditEntryEntity", b =>
                {
                    b.HasOne("Vectis.Web.Data.Entities.UserEntity", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Vectis.Web.Data.Entities.BabyEntity", b =>
                {
                    b.HasOne("Vectis.Web.Data.Entities.FamilyEntity", null)
                        .WithMany()
                        .HasForeignKey("FamilyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Vectis.Web.Data.Entities.FamilyEntity", b =>
                {
                    b.HasOne("Vectis.Web.Data.Entities.UserEntity", null)
                        .WithMany()
                        .HasForeignKey("CreatorUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Vectis.Web.Data.Entities.FamilyInvitationEntity", b =>
                {
                    b.HasOne("Vectis.Web.Data.Entities.FamilyEntity", null)
                        .WithMany()
                        .HasForeignKey("FamilyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Vectis.Web.Data.Entities.UserEntity", null)
                        .WithMany()
                        .HasForeignKey("InvitedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Vectis.Web.Data.Entities.FamilyMemberEntity", b =>
                {
                    b.HasOne("Vectis.Web.Data.Entities.FamilyEntity", null)
                        .WithMany()
                        .HasForeignKey("FamilyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Vectis.Web.Data.Entities.UserEntity", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Vectis.Web.Data.Entities.FeedingEntity", b =>
                {
                    b.HasOne("Vectis.Web.Data.Entities.BabyEntity", null)
                        .WithMany()
                        .HasForeignKey("BabyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Vectis.Web.Data.Entities.UserEntity", null)
                        .WithMany()
                        .HasForeignKey("FedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Vectis.Web.Data.Entities.PreparedBottleEntity", null)
                        .WithMany()
                        .HasForeignKey("PreparedBottleId")
                        .OnDelete(DeleteBehavior.SetNull);
                });

            modelBuilder.Entity("Vectis.Web.Data.Entities.MilkContainerEntity", b =>
                {
                    b.HasOne("Vectis.Web.Data.Entities.BabyEntity", null)
                        .WithMany()
                        .HasForeignKey("BabyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Vectis.Web.Data.Entities.PumpingSessionEntity", null)
                        .WithMany()
                        .HasForeignKey("PumpingSessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Vectis.Web.Data.Entities.NotificationDeliveryEntity", b =>
                {
                    b.HasOne("Vectis.Web.Data.Entities.FamilyEntity", null)
                        .WithMany()
                        .HasForeignKey("FamilyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Vectis.Web.Data.Entities.NotificationPreferencesEntity", b =>
                {
                    b.HasOne("Vectis.Web.Data.Entities.FamilyEntity", null)
                        .WithMany()
                        .HasForeignKey("FamilyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Vectis.Web.Data.Entities.PreparedBottleEntity", b =>
                {
                    b.HasOne("Vectis.Web.Data.Entities.BabyEntity", null)
                        .WithMany()
                        .HasForeignKey("BabyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Vectis.Web.Data.Entities.UserEntity", null)
                        .WithMany()
                        .HasForeignKey("PreparedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Vectis.Web.Data.Entities.PreparedBottleSourceEntity", b =>
                {
                    b.HasOne("Vectis.Web.Data.Entities.MilkContainerEntity", null)
                        .WithMany()
                        .HasForeignKey("ContainerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Vectis.Web.Data.Entities.PreparedBottleEntity", null)
                        .WithMany()
                        .HasForeignKey("PreparedBottleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Vectis.Web.Data.Entities.PumpingSessionEntity", b =>
                {
                    b.HasOne("Vectis.Web.Data.Entities.BabyEntity", null)
                        .WithMany()
                        .HasForeignKey("BabyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Vectis.Web.Data.Entities.UserEntity", null)
                        .WithMany()
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Vectis.Web.Data.Entities.StockMovementEntity", b =>
                {
                    b.HasOne("Vectis.Web.Data.Entities.MilkContainerEntity", null)
                        .WithMany()
                        .HasForeignKey("ContainerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Vectis.Web.Data.Entities.UserEntity", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
